---
name: Dependabot Pants Lockfile Update
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - poetry.lock

jobs:
  update-lockfiles:
    name: Update Pants Lockfiles
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up pants
        uses: pantsbuild/actions/init-pants@v7-scie-pants
        with:
          gha-cache-key: v0
          named-caches-hash: ${{ hashFiles('3rdparty/python/default.lock') }}
      - name: Generate lockfiles
        run: |
          pants generate-lockfiles ::
      - name: Commit and push changes
        run: |
          git config --global user.name 'dependabot[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add 3rdparty
          git diff --staged --quiet || (git commit -m "[automatic] update pants lockfiles" \
            && git push origin HEAD:${{ github.event.pull_request.head.ref }})
