---
name: Trigger Regybox Holidays
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule: # 48 hours in advance
    # Dia de Ano Novo
    # Sexta-Feira Santa
    # Páscoa
    # DST starts
    - cron: 50 8 23 4 * # 25 de Abril
    - cron: 50 8 29 4 * # Dia do Trabalhador
    # Corpo de Deus
    # Assunção de Nossa Senhora
    - cron: 50 8 8 6 * # Dia de Portugal
    - cron: 50 8 3 10 * # Implantação da República
    # DST ends
    - cron: 50 9 30 10 * # Dia de Todos os Santos
    - cron: 50 9 29 11 * # Restauração da Independência
    - cron: 50 9 6 12 * # Dia da Imaculada Conceição
    # Natal

jobs:
  weekday:
    name: Check weekday
    runs-on: ubuntu-latest
    outputs:
      weekday: ${{ steps.set.outputs.WEEKDAY }}
    steps:
      - id: set
        run: |
          echo "WEEKDAY=$([[ "$(date -d '+2 days' +%u)" -lt 6 ]] && echo "true" || echo "false")" >> "$GITHUB_OUTPUT"
  enroll:
    name: Trigger Regybox enrollment
    runs-on: ubuntu-latest
    needs:
      - weekday
    # only for holidays that are not on weekends
    if: needs.weekday.outputs.WEEKDAY == 'true'
    steps:
      - name: Regybox auto enrollment
        uses: martimlobao/regybox@main
        with:
          class-time: 10:00
          class-type: Weekend WOD Rato
          class-date-offset-days: 2
          phpsessid: ${{ secrets.PHPSESSID }}
          regybox-user: ${{ secrets.REGYBOX_USER }}
          calendar-url: ${{ secrets.CALENDAR_URL }}
          send-email: true
          email-to: ${{ secrets.EMAIL_TO }}
          email-username: ${{ secrets.EMAIL_USERNAME }}
          email-password: ${{ secrets.EMAIL_PASSWORD }}
