---
name: Trigger Regybox Holidays
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule: # 48 hours in advance
    # Dia de Ano Novo
    # Sexta-Feira Santa
    # Páscoa
    # DST starts
    - cron: 50 8 23 4 * # 25 de Abril
    - cron: 50 8 29 4 * # Dia do Trabalhador
    # Corpo de Deus
    # Assunção de Nossa Senhora
    - cron: 50 8 8 6 * # Dia de Portugal
    - cron: 50 8 3 10 * # Implantação da República
    # DST ends
    - cron: 50 9 30 10 * # Dia de Todos os Santos
    - cron: 50 9 29 11 * # Restauração da Independência
    - cron: 50 9 6 12 * # Dia da Imaculada Conceição
    # Natal

jobs:
  weekday:
    name: Check weekday
    runs-on: ubuntu-latest
    outputs:
      weekday: ${{ steps.set.outputs.WEEKDAY }}
    steps:
      - id: set
        run: |
          echo "WEEKDAY=$([[ "$(date -d '+2 days' +%u)" -lt 6 ]] && echo "true" || echo "false")" >> "$GITHUB_OUTPUT"
  build:
    name: Trigger Regybox run
    runs-on: ubuntu-latest
    needs:
      - weekday
    # only for holidays that are not on weekends
    if: needs.weekday.outputs.WEEKDAY == 'true'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up pants
        uses: pantsbuild/actions/init-pants@v10
        with:
          gha-cache-key: ${{ runner.os }}-pants-init-${{ hashFiles('pants.toml') }}
          named-caches-hash: ${{ hashFiles('3rdparty/python/default.lock') }}
      - name: Get class date
        run: |
          echo "CLASS_DATE=$(date -d '+2 days' +%F)" >> $GITHUB_ENV
          echo "CLASS_TIME='10:00'" >> $GITHUB_ENV
          echo "CLASS_TYPE='Weekend WOD Rato'" >> $GITHUB_ENV
      - name: Regybox enroll
        run: pants run regybox:main -- ${{ env.CLASS_DATE }} ${{ env.CLASS_TIME }} ${{ env.CLASS_TYPE }}
        env:
          PHPSESSID: ${{ secrets.PHPSESSID }}
          REGYBOX_USER: ${{ secrets.REGYBOX_USER }}
          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            Regybox HOLIDAY Auto-enroll: ${{ job.status }} for ${{ env.CLASS_TYPE }} on ${{ env.CLASS_DATE }}
            at ${{ env.CLASS_TIME }}
          body: >
            Job '${{ github.job }}' in worflow ${{ github.workflow }} of ${{ github.repository }} finished in a
            ${{ job.status }} state.

            See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          to: ${{ secrets.EMAIL_TO }}
          from: Regybox Auto-enroll
