---
name: Book my Regybox class

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule: # 60 hours in advance for morning classes
    # standard time, will be off on the last week of march
    - cron: 15 18 * 1-3,11-12 5-6,0-2
    # daylight saving time, will be off on the last week of october
    - cron: 15 17 * 4-10 5-6,0-2

jobs:
  enroll:
    runs-on: ubuntu-latest
    steps:
      - name: Run the Regybox Auto Enroll action
        uses: martimlobao/regybox@main
        with:
          class-time: 06:30
          class-type: WOD Rato
          class-date-offset-days: 3
          phpsessid: ${{ secrets.PHPSESSID }}
          regybox-user: ${{ secrets.REGYBOX_USER }}
          calendar-url: ${{ secrets.CALENDAR_URL }}
          send-email: true
          email-to: ${{ secrets.EMAIL_TO }}
          email-username: ${{ secrets.EMAIL_USERNAME }}
          email-password: ${{ secrets.EMAIL_PASSWORD }}
